session:
  key: <your_key>
admin:
  email: <your_email>
  password: <your_password>
database:
  host: database
  port: 5432
  user: <your_username>
  password: <your_password>
  database: <your_database_name>
rabbitmq:
  host: rabbitmq
  port: 5672
  user: <your_username>
  password: <your_password>
  queue: vk_updates
bot:
  token: <your_token>
  group_id: <your_group_id>
