session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: database
  port: 5432
  user: postgres
  password: dtKLoAJNzWsCewbah20W
  database: aiohttp_black_jack
rabbitmq:
  host: rabbitmq
  port: 5672
  user: rmuser
  password: DAs23orG23dvsESWFvda
  queue: vk_updates
bot:
  token: vk1.a.O6yYsUun9bUQScVqfK6lWSz7BYmXbYzNLhBMKnXu7yPk8Lj4oWXrzT984bMVSX_8Re3xeFED4uMCgQ9uOKVnew89sfnKVS-TkVr7ZJDNSNPdgCzbngShuzSMMyq_fbmxFknZhvObNaQTsT9X_kparDbHF8IJbpJFj4fQ_78tLCEq8wEA_Upj-DDJfB1KWoLzlAjpQypW3P9eU5tP7ZLuhw
  group_id: 218833701