version: "3.9"

services:

  database:
    container_name: database
    hostname: database
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_DB: "aiohttp_black_jack"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dtKLoAJNzWsCewbah20W"
    volumes:
      - ./docker/postgres:/var/lib/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: "rabbitmq:alpine"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rmuser"
      RABBITMQ_DEFAULT_PASS: "DAs23orG23dvsESWFvda"
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
     - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  admin-api:
    container_name: admin-api
    hostname: admin-api
    build: .
    restart: always
    ports:
      - "8080:8080"
    command: bash -c "export PYTHONPATH=. && alembic upgrade head && python main.py -s admin-api"
    depends_on:
      database:
         condition: service_healthy

  vk-poller:
    container_name: vk-poller
    hostname: vk-poller
    build: .
    restart: always
    ports:
      - "8081:8081"
    command: bash -c "python main.py -s vk-poller"
    depends_on:
      admin-api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  vk-worker:
    container_name: vk-worker
    hostname: vk-worker
    build: .
    restart: always
    ports:
      - "8082:8082"
    command: bash -c "python main.py -s vk-worker"
    depends_on:
      admin-api:
        condition: service_started
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy