"""Create database for black_jack game

Revision ID: fc24b5d6876f
Revises: 80eccf545808
Create Date: 2023-03-01 22:27:50.160230

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc24b5d6876f'
down_revision = '80eccf545808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'games', 'players', ['current_player_id'], ['player_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    # ### end Alembic commands ###
