name: Build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_push:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
                  
      - name: "Build and push"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker-compose.yml
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}
          secrets: |
            "github_token=${{ secrets.REGISTRY_TOKEN }}"
          


      

