name: Build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          
      - name: "Build image"
        run: docker compose -f docker-compose.yml build
        
      - name: "Push image"
        run: docker compose -f docker-compose.yml push
          


      

